<?php require('template/header.phtml') ?>

<h3>Most recent adverts</h3>
    <script type="text/javascript">
        var off = 1;
        function loadAds(offset){
            var xhr = new XMLHttpRequest();
            xhr.open('POST', 'nextads.php');
            xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
            xhr.onreadystatechange = function(){
                var DONE = 4;
                var OK = 200;
                if(xhr.readyState === DONE)
                    document.getElementById("adspace").innerHTML += xhr.responseText;
                console.log(xhr.responseText);
                console.log(off);
            }
            xhr.send("offset="+off);
            off ++;
        }
    </script>
<a href="javascript:loadAds()">load</a>
<ul>
    <div id="adspace" class="row">
    </div>
</ul>
    <div class="row">
        <ul class="pagination">
            <li <?php if($view->offset == 1) echo 'class="active"';?>><a href="index.php?limit=<?php echo $view->limit.'&offset=1';?>">First</a></li>
            <?php if($view->offset -2 > 0):?>
                <li><a href="index.php?limit=<?php echo $view->limit ?>&offset=<?php echo $view->offset -2;?>"><?php echo $view->offset -2;?></a></li>
            <?php endif;?>
            <?php if($view->offset -1 > 0):?>
                <li><a href="index.php?limit=<?php echo $view->limit ?>&offset=<?php echo $view->offset -1;?>"><?php echo $view->offset -1;?></a></li>
            <?php endif;?>
            <li class="active"><a href="index.php?limit=<?php echo $view->limit ?>&offset=<?php echo $view->offset;?>"><?php echo $view->offset;?></a></li>
            <?php if(isset($view->count)):?>
                <?php if($view->offset*$view->limit < $view->count):?>
                    <li><a href="index.php?limit=<?php echo $view->limit ?>&offset=<?php echo $view->offset +1;?>"><?php echo $view->offset +1;?></a></li>
                <?php endif;?>
                <?php if(($view->offset +1)*$view->limit < $view->count):?>
                    <li><a href="index.php?limit=<?php echo $view->limit ?>&offset=<?php echo $view->offset +2;?>"><?php echo $view->offset +2;?></a></li>
                <?php endif;?>
                <li <?php if(($view->offset)*$view->limit > $view->count) echo 'class="active"';?>><a href="index.php?limit=<?php echo $view->limit.'&offset=last';?>">Last</a></li>
            <?php elseif($view->total%$view->limit ==0):?>
                <li class="active"><a href="index.php?limit=<?php echo $view->limit ?>&offset=<?php echo $view->offset+1;?>"><?php echo $view->offset+1;?></a></li>
            <?php endif?>
        </ul>
        <form class="navbar-form navbar-right" action="searchads.php" method="post" role="search">
            <div class="form-group input-group">
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">Adverts per page
                        <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                        <li <?php if($view->limit == 10) echo 'class="active"';?>><a href="<?php echo 'index.php?limit=10';?>">10</a></li>
                        <li <?php if($view->limit == 20) echo 'class="active"';?>><a href="<?php echo 'index.php?limit=20';?>">20</a></li>
                        <li <?php if($view->limit == 100) echo 'class="active"';?>><a href="<?php echo 'index.php?limit=100';?>">100</a></li>
                    </ul>
                </div>
            </div>
        </form>
    </div>


<?php require('template/footer.phtml'); ?>