<?php require('template/header.phtml') ?>

<h3>Most recent adverts</h3>
<ul>
<?php if(isset($view->ads) ){
    for ($i = 0; $i < $view->total; $i++) {
        $view->curAd = $i;
        require('template/thumbnail.phtml');
    }
}
?>
</ul>
<?php if(isset($view->status)) : ?>
    <div class="alert alert-<?php echo (isset($view->error) ? 'danger' : 'success'); ?>">
        <span class='glyphicon glyphicon-hand-up' aria-hidden='true'></span>
        <div>
            <?php echo $view->status; if(isset($view->error)): ?>
                <div>
                    <?php require('template/login.phtml'); ?>
                </div>
            <?php endif;?>
        </div>
    </div>
<?php endif;
require('template/footer.phtml'); ?>

