<?php require('template/header.phtml') ?>

    <h3>Most recent adverts</h3>
<a href="javascript:loadAds()">load</a>
    <ul>
        <div id="adspace">

        </div>
    </ul>
    <script src="../js/infinitescroll.js"></script>
    <script type="text/javascript">
        load();
        loadAds();
        function loadAds() {
            var xhr = new XMLHttpRequest();
            xhr.open('POST', 'nextads.php', true);
            xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
            xhr.onreadystatechange = function () {
                var DONE = 4;
                var OK = 200;
                if (xhr.readyState == DONE) {
                    document.getElementById("adspace").innerHTML += xhr.responseText;
                    console.log("off rec" + off);
                    send = true;
                }
                //console.log(xhr.responseText);
            }
            xhr.send("offset=" + off);
            console.log("off send" + off);
            off++;
        }
    </script>
<?php require('template/footer.phtml'); ?>