<?php require('template/header.phtml') ?>

<h3>Advert</h3>
<?php if(isset($view->adtitle))echo "<p>".$view->adtitle."</p>";
if(isset($view->desc))echo "<p>".$view->desc."</p>";
if(isset($view->price))echo "<p>".$view->price."</p>";
if(isset($view->aduser))echo "<p>".$view->aduser."</p>";
if(isset($view->digital))echo "<p>".$view->digital."</p>";
if(isset($view->img)) foreach($view->img as $img) echo "<img src='".$img."'>";
if(isset($view->watched)) {
    if ($view->watched)
        echo "<a href='advert.php?id=$view->id&w=0'> Un-watch </a>";
    else
        echo "<a href='advert.php?id=$view->id&w=1'> Watch </a>";
}
?>
<?php if(isset($view->status)) : ?>
    <div class="alert alert-<?php echo (isset($view->error) ? 'danger' : 'success'); ?>">
        <span class='glyphicon glyphicon-hand-up' aria-hidden='true'></span>
        <div>
            <?php echo $view->status; if(isset($view->error)): ?>
                <div>
                    <?php require('template/login.phtml'); ?>
                </div>
            <?php endif;?>
        </div>
    </div>
<?php endif;
require('template/footer.phtml'); ?>

