<?php require('template/header.phtml') ?>
<div class='panel panel-default'>
    <div class='panel-heading'>
        <div class="row">
            <div class="col-sm-5">
                <?php if(isset($view->adtitle))echo "<h3>".$view->adtitle."</h3>"; ?>
            </div>
            <div class="col-sm-5">
                <?php if(isset($view->price))echo "<h3>£".$view->price."</h3>"; ?>
            </div>
            <div class="col-sm-2 pull-right">
                <h3><span class="label label-info"><?php if(isset($view->digital)){
                            if($view->digital == 1)
                                echo "Digital";
                            else
                                echo "Physical";
                        } ?></span></h3>
            </div>
        </div>
    </div>
    <div class='panel-body'>
        <div class="row">
            <ul>
                <?php if(isset($view->img)) foreach($view->img as $img): ?>
                    <div class="col-md-3">
                        <div class="thumbnail">
                            <img src="<?php echo $img; ?>">
                        </div>
                    </div>
                <?php endforeach;?>
            </ul>
        </div>
        <p><?php if(isset($view->desc))echo $view->desc; ?></p>
    </div>
    <div class="panel-footer">
        <?php if(isset($view->watched)): ?>
        <div class="row">
            <div class="col-sm-6">
                <?php
                    if ($view->watched)
                        echo "<a class='btn btn-default' href='advert.php?id=$view->id&w=0'> Un-watch </a>";
                    else
                        echo "<a  class='btn btn-primary' href='advert.php?id=$view->id&w=1'> Watch </a>";
                ?>
            </div>
            <div class="col-sm-6">
                <?php if(isset($view->aduser))echo "<a class='btn btn-default' href='user.php?id=$view->aduser'>User - $view->aduser </a>";?>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>
<?php require('template/footer.phtml'); ?>

