<?php require('template/header.phtml') ?>

<h3>New Advert</h3>
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label class="control-label col-sm-2" for="title">Title: </label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="title" name="title" value="" required/>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="desc">Description: </label>
            <div class="col-sm-10">
                <textarea class="form-control" id="desc" name="desc" value=""></textarea>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="price">Price: </label>
            <div class="col-sm-10">
                <input type="number" step="0.01" min="0" max="9999.99" name="price" value="" class="form-control" id="price" required/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                    <label><input type="checkbox" name="digital" checked> Is this piece digital?</label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="file">Image(s): </label>
            <div class="col-sm-10">
                <input type="file" name="fileToUpload[]" multiple="multiple" class="form-control" id="file" accept="image/gif,image/bmp,image/jpeg,image/png"/>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input id="submit-btn" class="btn btn-default" type="submit" value="Create" name="submit" />
            </div>
        </div>
    </form>
<?php require('template/footer.phtml'); ?>