<?php require('template/header.phtml') ?>

<h3>New Advert</h3>
<form action="" method="post" enctype="multipart/form-data">
    <div>
        <label>Title: </label>
        <input type="text"  name="title" value=""/>
        <label>Description: </label>
        <input type="text"  name="desc" value=""/>
        <label>Price: </label>
        <input type="text"  name="price" value=""/>
        <label>Image(s): </label>
        <input type="file"  name="fileToUpload" value=""/>

        <input class="btn" type="submit" value="Login" name="submit" />
    </div>
</form>
<?php require('template/footer.phtml'); ?>