<?php require('template/header.phtml') ?>

<h3>Register</h3>
<form action="" method="post">
    <div>
        <label>Email: </label>
        <input type="text"  name="username" value=""/>
        <label>Password: </label>
        <input type="text"  name="password" value=""/>
        <input class="btn" type="submit" value="Register" name="submit" />
    </div>
</form>
<?php if(isset($view->status)) : ?>
    <div class="alert alert-<?php echo (isset($view->error) ? 'danger' : 'success'); ?>">
        <span class='glyphicon glyphicon-hand-up' aria-hidden='true'></span>
        <div> <?php echo $view->status;
            if($view->error == 1): ?>
                <div>
                    <?php require('template/login.phtml'); ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php endif;
require('template/footer.phtml'); ?>

