<?php require('template/header.phtml') ?>

<h3>Register</h3>

<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label class="control-label col-sm-2" for="username">Email: </label>
        <div class="col-sm-10">
            <input type="email" class="form-control" id="username" name="username" value="" required/>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="password">Password: </label>
        <div class="col-sm-10">
            <input type="password" class="form-control" id="password" name="password" value="" required/>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="addr1">Address line 1: </label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="addr1" name="address1" value=""/>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="addr2">Address line 2: </label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="addr2" name="address2" value=""/>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="mob">Mobile phone number: </label>
        <div class="col-sm-10">
            <input type="tel" maxlength="12" class="form-control" id="mob" name="mobile" value="" required/>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="cap">Enter the text in the image: </label>
        <img class="col-sm-2 img-rounded" src="/image.php" id="captcha-img">
        <div class="col-sm-8">
            <input type="text" class="form-control" id="cap" name="captcha" value=""/>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <input id="submit-btn" class="btn btn-default" type="submit" value="Register" name="submit" />
        </div>
    </div>
</form>
<?php if(isset($view->status)) : ?>
    <div class="alert alert-<?php echo (isset($view->error) ? 'danger' : 'success'); ?>">
        <span class='glyphicon glyphicon-hand-up' aria-hidden='true'></span>
        <div>
            <?php echo $view->status; if(isset($view->error)): ?>
                <div>
                    <?php require('template/login.phtml'); ?>
                </div>
            <?php endif;?>
        </div>
    </div>
<?php endif;
require('template/footer.phtml'); ?>

