

    <h1>Remote</h1>
    <script src="js/command.js"></script>
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button id="submit-btn" class="btn btn-default" type="button"onclick="sendComm('play')"><h2>Play/Pause</h2></button>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button id="submit-btn" class="btn btn-default" type="button"onclick="sendComm('skip')"><h2>Skip</h2></button>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button id="submit-btn" class="btn btn-default" type="button"onclick="sendComm('rewind')"><h2>Rewind</h2></button>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button id="submit-btn" class="btn btn-default" type="button"onclick="sendComm('forward')"><h2>Forward</h2></button>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button id="submit-btn" class="btn btn-default" type="button"onclick="sendComm('full')"><h2>Full Screen</h2></button>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button id="submit-btn" class="btn btn-default" type="button"onclick="sendComm('min')"><h2>Exit Full Screen</h2></button>
            </div>
        </div>

    </form>
    <script src="js/command.js"></script>