<?php require('template/header.phtml') ?>

<h3>Search Adverts</h3>
<form action="" method="post" enctype="multipart/form-data">
    <div>
        <label>Title: </label>
        <input type="text"  name="title" value=""/>
        <label>Description: </label>
        <input type="text"  name="desc" value=""/>
        <label>Min-price: </label>
        <input type="number" step="0.01" min="0" max="9999.99" name="minprice" value=""/>
        <label>Max-price: </label>
        <input type="number" step="0.01" min="0" max="9999.99" name="maxprice" value="9999.99"/>
        <label>Digital: </label>
        <input type="checkbox" name="digital" checked value=""/>
        <label>Real: </label>
        <input type="checkbox" name="notdigital" checked value=""/>

        <input id="submit-btn" class="btn" type="submit" value="Search" name="submit" />
    </div>
</form>
    <ul>
        <?php if(isset($view->ads) ){
            for ($i = 0; $i < $view->total; $i++) {
                $view->curAd = $i;
                require('template/thumbnail.phtml');
            }
        }
        ?>
    </ul>
<?php require('template/footer.phtml'); ?>