<?php require('template/header.phtml') ?>

    <h3>Search Adverts</h3>

    <div id="formcont" class="col-sm-9">
        <form class="form-horizontal"  enctype="multipart/form-data" id="searchform" onkeyup="search()" onchange="search()">
            <div class="form-group">
                <label class="control-label col-sm-4" for="title">Keywords: </label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="title" name="title" value="<?php if(isset($view->title))echo $view->title; ?>"/>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-4" for="minprice">Min-price: </label>
                <div class="col-sm-8">
                    <input type="number" min="0" max="9999.99" name="minprice" value="" class="form-control" id="minprice"/>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-4" for="maxprice">Max-price: </label>
                <div class="col-sm-8">
                    <input type="number" min="0" max="9999.99" name="maxprice" value="" class="form-control" id="maxprice"/>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-4 col-sm-8">
                    <div class="checkbox">
                        <label><input type="checkbox" name="digital" checked> Digital</label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-4 col-sm-8">
                    <div class="checkbox">
                        <label><input type="checkbox" name="notdigital" checked> Physical</label>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-4 col-sm-8">
                    <input id="submit-btn" class="btn btn-default" type="button" value="Search" name="submit" onclick="search()"/>
                </div>
            </div>
        </form>
    </div>

    <div class="col-sm-9">
        <ul>
            <div id="adspace" class="row">

            </div>
        </ul>
    </div>

    <script src="/js/infinitescroll.js"></script>
    <script type="text/javascript">
        formdata = true;
        file = 'searchnextads.php';
        function search(){
            document.getElementById("adspace").innerHTML = "";
            data = new FormData(document.getElementById("searchform"));
            off = 1;
            document.getElementById("formcont").className = "col-sm-3";
            loadAds()
        }
        load();
        <?php if(isset($view->title)) echo "search();"; ?>
    </script>
<?php require('template/footer.phtml'); ?>