<?php require('template/header.phtml') ?>

    <h3>Search Adverts</h3>

    <div class="col-sm-<?php if(isset($view->ads) ) echo "3"; else echo "9";?>">
        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label class="control-label col-sm-4" for="title">Keywords: </label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="title" name="title" value=""/>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-4" for="minprice">Min-price: </label>
                <div class="col-sm-8">
                    <input type="number" step="0.01" min="0" max="9999.99" name="minprice" value="" class="form-control" id="minprice"/>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-4" for="minprice">Max-price: </label>
                <div class="col-sm-8">
                    <input type="number" step="0.01" min="0" max="9999.99" name="maxprice" value="9999.99" class="form-control" id="maxprice"/>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-4 col-sm-8">
                    <div class="checkbox">
                        <label><input type="checkbox" name="digital" checked> Digital</label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-4 col-sm-8">
                    <div class="checkbox">
                        <label><input type="checkbox" name="notdigital" checked> Physical</label>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-4 col-sm-8">
                    <input id="submit-btn" class="btn btn-default" type="submit" value="Search" name="submit" />
                </div>
            </div>
        </form>
    </div>
<?php if(isset($view->ads) ): ?>
    <div class="col-sm-9">
        <ul>
            <?php
            for ($i = 0; $i < $view->total; $i++) {
                $view->curAd = $i;
                require('template/thumbnail.phtml');
            }?>
        </ul>
    </div>
<?php endif;?>
<?php require('template/footer.phtml'); ?>