<?php require('template/header.phtml') ?>

<h3>Login</h3>
 <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label class="control-label col-sm-2" for="username">Email: </label>
                <div class="col-sm-10">
                    <input type="email" class="form-control" id="username" name="username" value=""/>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="password">Password: </label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" id="password" name="password" value=""/>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <input id="submit-btn" class="btn btn-default" type="submit" value="Login" name="submit" />
                </div>
            </div>

     <div class="form-group">
         <div class="col-sm-offset-2 col-sm-10">
             <a href="register.php">Not registered already? Click here.</a>
         </div>
     </div>
 </form>
<?php if(isset($view->status)) : ?>
    <div class="alert alert-danger">
        <span class='glyphicon glyphicon-hand-up' aria-hidden='true'></span>
        <?php echo $view->status; ?>
    </div>
<?php endif;
require('template/footer.phtml'); ?>