<?php require('template/header.phtml') ?>

<h3>Login</h3>
<form action="" method="post">
    <div>
        <label>Email: </label>
        <input type="text"  name="username" value=""/>
        <label>Password: </label>
        <input type="text"  name="password" value=""/>
        <input class="btn" type="submit" value="Login" name="submit" />
    </div>
</form>
<div><a href="register.php">Not registered already? Click here.</a></div>
<?php if(isset($view->status)) : ?>
    <div class="alert alert-success">
        <span class='glyphicon glyphicon-hand-up' aria-hidden='true'></span>
        <div> <?php echo $view->status; ?> </div>
    </div>
<?php endif;
require('template/footer.phtml'); ?>