<?php require('template/header.phtml') ?>

<h3 class=" col-sm-4 col-sm-offset-4">All Registered Users</h3>
<ul class="list-group col-sm-4 col-sm-offset-4">
<?php if(isset($view->users) ){
    foreach ($view->users as $user) {
        echo "<li class='list-group-item row'> <a href='user.php?id=$user[0]' >$user[0]</a><a class='btn btn-default pull-right' href='userlist.php?id=$user[0]'> Delete </a></li>";
    }
}
?>
</ul>
<?php require('template/footer.phtml'); ?>

