<?php require('template/header.phtml') ?>
<ul class="list-group">
    <li class="list-group-item list-group-item-info">
        <h4 class="list-group-item-heading">Email:</h4>
        <p class="list-group-item-text"> <?php echo $view->username; ?></p>
    </li>
    <li class="list-group-item">
        <h4 class="list-group-item-heading">Address Line 1:</h4>
        <p class="list-group-item-text"> <?php echo $view->address1; ?></p>
    </li>
    <li class="list-group-item">
        <h4 class="list-group-item-heading">Address Line 2:</h4>
        <p class="list-group-item-text"> <?php echo $view->address2; ?></p>
    </li>
    <li class="list-group-item">
        <h4 class="list-group-item-heading">Mobile Phone Number:</h4>
        <p class="list-group-item-text"> <?php echo $view->mobile; ?></p>
    </li>
</ul>

<?php if(isset($view->user)) if($view->user === "admin@admin" || $view->user === $view->username):?>
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label class="control-label col-sm-2" for="password">Password: </label>
            <div class="col-sm-10">
                <input type="password" class="form-control" id="password" name="password" value="" required/>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="addr1">Address line 1: </label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="addr1" name="address1" value=" <?php echo $view->address1; ?>"/>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="addr2">Address line 2: </label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="addr2" name="address2" value="<?php echo $view->address2; ?>"/>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="mob">Mobile phone number: </label>
            <div class="col-sm-10">
                <input type="tel" maxlength="12" class="form-control" id="mob" name="mobile" value="<?php echo $view->mobile; ?>" required/>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input id="submit-btn" class="btn btn-default" type="submit" value="Submit" name="submit" />
                <a class='btn btn-default pull-right' href='userlist.php?id=<?php echo $view->username; ?>'> Delete Account </a>
            </div>

        </div>
    </form>
    <?php if(isset($view->status)) : ?>
        <div class="alert alert-danger">
            <span class='glyphicon glyphicon-hand-up' aria-hidden='true'></span>
            <?php echo $view->status; ?>
        </div>
    <?php endif; endif;
require('template/footer.phtml'); ?>

