<?php require('template/header.phtml') ?>

<h3>Your watched adverts</h3>
<!--<div>-->
<!--<ul>-->
<?php //if(isset($view->ads) ){
//    $view->watch = true;
//    for ($i = 0; $i < $view->total; $i++) {
//        $view->curAd = $i;
//        require('template/thumbnail.phtml');
//    }
//}
//?>
<!--</ul>-->
<!--    -->
<!--</div>-->
<ul>
    <div id="adspace">

    </div>
</ul>
<div id="loading-div"><div id="loading-symbol"></div><p>Loading...</p></div>
<script src="js/infinitescroll.js"></script>
<script type="text/javascript">
    file = 'watchnextads.php';
    load();
    loadAds();
</script>
<?php require('template/footer.phtml'); ?>

