<?php require('template/header.phtml') ?>

<h3>How This Template Works</h3>
<p>
    The controller creates a model to store information about the attributes
    on the page. In this template the .php files create a stdClass to store
    the title of the page. The main view for the page is then loaded using
    the require_once method which loads the specific .phtml file for that page.
    The .phtml file uses the require method to load the header and footer views.
    The header and footer views are general for each page but get the page attributes
    from the model to disply it in the page.

</p>

<?php require('template/footer.phtml') ?>
