<?php require('template/header.phtml') ?>
<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
    <div>
        <label>Calculate </label>
        <input type="number" step="any" name="number1" value="<?php if (isset($_POST['number1'])) {
            echo $_POST['number1']; 	} ?>"/>
        <select name="operation" class="">
            <option>+</option>
            <option>-</option>
            <option>*</option>
            <option>/</option>
        </select>
        <input type="number" step="any" name="number2" value="<?php if (isset($_POST['number2'])) {
            echo $_POST['number2']; 	} ?>"/>
        <input class="btn" type="submit" value="submit" name="submit" />
    </div>
</form>
<div class="col-lg-3 col-lg-offset-1 alert alert-<?php if (isset($view->error)) echo $view->error; ?>">
    <span class="glyphicon glyphicon-<?php if (isset($view->glyph)) echo $view->glyph; ?>" aria-hidden="true"></span>
<?php if (isset($view->result)) echo $view->result;?>
</div>
<?php require('template/footer.phtml') ?>