<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="/css/my-style.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <title>Sell your art - <?php echo $view->pageTitle; ?></title>
</head>

<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <span class="navbar-brand"><?php echo $view->pageTitle; ?></span>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li><a href="index.php"">Latest Ads</a></li>
                <li><a href="searchads.php">Advanced Search</a></li>
            </ul>

            <form class="navbar-form navbar-right" action="searchads.php" method="post" role="search">
                <div class="form-group input-group">
                    <input type="search" class="form-control" name="title" placeholder="Search..">
                    <span class="input-group-btn">
            <button class="btn btn-default" id="submit-btn" type="submit" value="Search" name="submit" >
              <span class="glyphicon glyphicon-search"></span>
            </button>
          </span>
                </div>
            </form>

            <ul class="nav navbar-nav navbar-right">
                 <?php if(isset($view->user))require('logout.phtml');else require('login.phtml');?>
            </ul>
        </div>
    </div>
</nav>

<div class="container">



