
<div class="dropdown">
    <button class="btn dropdown-toggle"  id="user-btn" type="button" data-toggle="dropdown"><h4>Hello <?php echo $view->user; ?>
        <span class="caret"></span></h4></button>
    <ul class="dropdown-menu">
        <li><a href="createadvert.php">Sell a new peice</a></li>
        <li><a href="watchadlist.php">View Watch list</a></li>
        <li><a href="logout.php">Logout</a></li>
    </ul>
</div>