<?php if($view->curAd%4 == 0) echo '</div><div class="row">';?>
<div class="col-md-3">
    <div class="thumbnail">
        <a href="advert.php?id=<?php echo $view->ads[$view->curAd][0]; ?>">
            <img src="<?php echo $view->img[$view->curAd]; ?>" alt="Ad" style="width:100%">
            <div class="caption">
                <h4><?php echo $view->ads[$view->curAd][1]."</h4><h4>£". $view->ads[$view->curAd][2]; ?></h4>
                <?php if(isset($view->watch)){
                    $id = $view->ads[$view->curAd][0];
                    echo "<a class='btn btn-default' href='watchadlist.php?id=$id&w=0'> Un-watch </a>";
                }  ?>
            </div>
        </a>
    </div>
</div>